import { EmptyState } from "../../components/ui/EmptyState";
import { KpiCard } from "../../components/ui/KpiCard";
import { NextActionCard } from "../../components/ui/NextActionCard";
import { PageContainer } from "../../components/ui/PageContainer";
import { PageHeroSummary } from "../../components/ui/PageHeroSummary";


export function DocumentNumbering() {
  return (
    <PageContainer>
      <PageHeroSummary
        eyebrow="Admin Console"
        title="Document Numbering"
        subtitle="Document numbering rules will control unique identifiers across brands, markets, channels, and versions."
        status="PENDING"
        statusLabel="Future Configuration"
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Prefix Rules" value={0} helperText="No custom rules" status="neutral" />
        <KpiCard label="Sequence Format" value="Default" helperText="Backend controlled" status="info" />
        <KpiCard label="Market Codes" value={0} helperText="Future mapping" status="neutral" />
        <KpiCard label="Version Labels" value="v1" helperText="Current version format" status="success" />
      </div>

      <EmptyState
        title="Numbering configuration is not active yet"
        description="Prefix rules, sequence formats, market codes, and version labels will be configurable in a future phase."
      />

      <NextActionCard
        title="Use the existing document number generated by the backend."
        description="UI-1 does not change document numbering APIs or introduce new numbering behavior."
      />
    </PageContainer>
  );
}
